/**
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
**/

#ifndef ORG_CONSOLE_LIB_CFG_DEFINES_HPP
#define ORG_CONSOLE_LIB_CFG_DEFINES_HPP

// DEBUG
#ifdef DEBUG

// Exceptions throw def.
#define THROWABLE
#else // !DEBUG

// Exceptions throw def.
#define THROWABLE noexcept
#endif
// DEBUG

#endif // !ORG_CONSOLE_LIB_CFG_DEFINES_HPP